### ISSUE TITLE
Read Please

### ISSUE THREAD

**Issue by PixlPlcr** [Plugins4Unturned/CustomKits#1]
So as i Installed your plugin I got frustrated when The custom Kits only saved to StoredKits.json when the server was Shut down. So (this is more of a recommendation) If possible, Could you make it save every time the server is saved? 

I always worry about server Crashes and losing the players custom kits. This is one of the only things on my mind about my server. I do have server Restart scripts and plugins running but those i consider Unreliable.

More of a recommendation not an 'issue' (it is on my part :P) 

                                                     -PixlPlcr owner of _[CA] Elite PvP [20+ Kits|Custom Kits|Shop|PvP]_

**Comment by Teyhota6** [comment]
added
